### ISSUE TITLE
`PPM` image read error

### ISSUE THREAD

**Issue by LuoZijun** [descampsa/yuv2rgb#4] opened 2016-12-05 04:11 UTC
the function `readPPM` at `test_yuv_rgb.c` looks not working.

![image](https://cloud.githubusercontent.com/assets/717717/20873598/ee0e951e-bae3-11e6-801f-19e73da7db8f.png)

**Comment by descampsa** [comment] 2016-12-05 12:58
Is it an image generated by the program itself (in yuv2rgb mode), or by an external editor?
Some editors add comments in the header, and that is not supported by the `readPPM` function.

**Comment by descampsa** [comment] 2016-12-07 20:10
Ok, i have fixed one bug, a string used in strcmp that was not nul terminated.
That was probably the cause of your problem.

Could you try again and confirm that the problem is fixed?
Thanks

**Comment by LuoZijun** [comment] 2016-12-08 07:28
the problem is already fixed.  👍

**Closed** 2016-12-08 08:30 UTC
